/*
  Warnings:

  - Changed the type of `type` on the `Like` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "LikeType" AS ENUM ('LIKE', 'DISLIKE');

-- AlterTable
-- Alter the column type in place, casting the existing string values to the new enum type.
-- Assumes existing values are exactly 'LIKE' or 'DISLIKE'. Add error handling/defaults if needed.
ALTER TABLE "Like" ALTER COLUMN "type" TYPE "LikeType" USING "type"::"LikeType";

-- The following lines generated by Prisma are replaced by the line above:
-- ALTER TABLE "Like" DROP COLUMN "type",
-- ADD COLUMN     "type" "LikeType" NOT NULL;
