name: Exponus Build Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # Common package tests
      - name: Install common dependencies
        working-directory: ./common
        run: npm ci
      
      - name: Lint common package
        working-directory: ./common
        run: npm run lint
      
      - name: Test common package
        working-directory: ./common
        run: npm test
      
      # Backend tests
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Lint backend
        working-directory: ./backend
        run: npm run lint
      
      - name: Test backend
        working-directory: ./backend
        run: npm test
      
      # Frontend tests
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint
      
      - name: Test frontend
        working-directory: ./frontend
        run: npm test
  
  build-and-push:
    needs: test-and-lint
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push backend
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            yourusername/exponus-backend:latest
            yourusername/exponus-backend:${{ github.sha }}
          cache-from: type=registry,ref=yourusername/exponus-backend:buildcache
          cache-to: type=registry,ref=yourusername/exponus-backend:buildcache,mode=max
      
      # Build and push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            yourusername/exponus-frontend:latest
            yourusername/exponus-frontend:${{ github.sha }}
          cache-from: type=registry,ref=yourusername/exponus-frontend:buildcache
          cache-to: type=registry,ref=yourusername/exponus-frontend:buildcache,mode=max
